# Generated by Django 5.1.1 on 2024-09-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTenantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('date', models.DateField(blank=True)),
            ],
        ),
    ]
