# Generated by Django 5.1.1 on 2024-09-14 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_addtenantmodel_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExpeseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=300)),
                ('item_price', models.IntegerField()),
                ('expenser_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addtenantmodel')),
            ],
        ),
    ]
