# Generated by Django 5.1.1 on 2024-09-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_addexpesemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_day', models.FloatField()),
                ('Per_member', models.FloatField()),
                ('No_of_days', models.IntegerField()),
                ('Amount_to_be_paid', models.FloatField()),
                ('name_of_expenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addtenantmodel')),
            ],
        ),
    ]
