# Generated by Django 5.1.1 on 2024-09-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_calculateexpensemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateexpensemodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
