# Generated by Django 5.1.1 on 2024-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_calculateexpensemodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculateexpensemodel',
            name='Amount_to_be_paid',
            field=models.FloatField(default=0),
        ),
    ]
