# Generated by Django 5.1.1 on 2024-09-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_calculateexpensemodel_amount_to_be_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculateexpensemodel',
            name='No_of_days',
        ),
        migrations.RemoveField(
            model_name='calculateexpensemodel',
            name='Per_member',
        ),
        migrations.RemoveField(
            model_name='calculateexpensemodel',
            name='per_day',
        ),
        migrations.AddField(
            model_name='calculateexpensemodel',
            name='food_expense',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculateexpensemodel',
            name='water_bill',
            field=models.FloatField(default=0),
        ),
    ]
