# Generated by Django 5.1.1 on 2024-09-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_calculateexpensemodel_no_of_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateexpensemodel',
            name='no_of_days',
            field=models.IntegerField(default=0),
        ),
    ]
