# Generated by Django 5.1.1 on 2024-09-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_calculateexpensemodel_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateexpensemodel',
            name='totol_amount',
            field=models.FloatField(default=0),
        ),
    ]
