# Generated by Django 5.1.1 on 2024-09-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_calculateexpensemodel_totol_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateexpensemodel',
            name='per_day',
            field=models.FloatField(default=0),
        ),
    ]
