# Generated by Django 5.1.1 on 2024-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_calculateexpensemodel_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateexpensemodel',
            name='electric_bill',
            field=models.FloatField(default=0),
        ),
    ]
